import { useEffect, useRef, useState } from "react";
import { getSignedUrl, uploadFile } from "../service/api";

function Home() {
  const fileSystemRef = useRef();

  const [url, setUrl] = useState("");
  const [file, setFile] = useState("");

  useEffect(() => {
    const getData = async () => {
      const response = await getSignedUrl();
      setUrl(response.url);
    };
    getData();
  }, []);

  // Call API after getting a file on that URL
  useEffect(() => {
    const getData = async () => {
      const response = await uploadFile(url, file);
    };
    file && getData();
  }, [file]);

  return (
    <>
      <div className=" mt-14 mb-10 mr-4 ml-4 text-center">
        <h1 className="font-mono text-3xl font-bold text-white mb-2">
          Generate your Video Tags
        </h1>
        <h2 className="text-lg">
          Upload your video and get tags for your socials, generated by
          GPT-3.5-turbo Model.
        </h2>
      </div>
      <div className="border-2 border-dashed border-white mt-7 mr-72 ml-72 p-10 text-center">
        <h1 className="text-2xl mb-4 text-white font-serif">
          <input
            type="file"
            ref={fileSystemRef}
            className="hidden"
            onChange={(e) => {
              setFile(e.target.files[0]);
            }}
          />
          <button
            onClick={() => {
              fileSystemRef.current.click();
            }}
          >
            Upload Video
          </button>
        </h1>
        {/* <Dropzone className="p-10 mt-6 border border-neutral-200" /> */}

        <h2>
          <a href={url.split("?")[0]}>{url.split("?")[0]}</a>
        </h2>
      </div>
    </>
  );
}

export default Home;
